### ISSUE TITLE
Is codecov broken for this package?

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/GeoJSON.jl#69]
When I looked at https://app.codecov.io/gh/JuliaGeo/GeoJSON.jl/tree/master/src?displayType=list, it seems to think the latest commit is https://github.com/JuliaGeo/GeoJSON.jl/commit/674f18a5c97877817650ba6bded23898f16c1425

**Comment by rafaqz** [comment]
Probably broken then, you are welcome to fix it ;)

**Comment by visr** [comment]
We use [`codecov/codecov-action@v1`](https://github.com/JuliaGeo/GeoJSON.jl/blob/b9825e924eaed4856bcaa7cdc55138e185a7a477/.github/workflows/CI.yml#L44), whereas the current version is v3. According to [this](https://github.com/codecov/codecov-action/releases/tag/v2.0.0) the v1 uploader has been sunset for a while, so that probably explains this issue.

In https://github.com/JuliaGeo/GDAL.jl/pull/154 I added dependabot for GDAL.jl, leading to PRs like https://github.com/JuliaGeo/GDAL.jl/pull/155 that fix this issue. Let's add dependabot to all JuliaGeo packages.
